networks:
  cluster_almacen_default:
services:
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=almacen
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  usuarios:
    #build: ./microservicios/usuarios
    image: mitgar14/usuarios-almacen
    ports:
      - "3001:3001"
    depends_on:
      - db
  productos:
    #build: ./microservicios/productos
    image: mitgar14/productos-almacen
    ports:
      - "3002:3002"
    depends_on:
      - db
  ordenes:
    #build: ./microservicios/ordenes
    image: mitgar14/ordenes-almacen
    ports:
      - "3003:3003"
    depends_on:
      - db
      - usuarios
      - productos
  web:
    #build: ./web
    image: mitgar14/web-almacen
    ports:
      - "8080:80"
    depends_on:
      - usuarios
      - productos
      - ordenes
